<?php  //[STAMP] a58c1acd52ca03198145acd24fb8c4f9
namespace PrivateIT\modules\mailQueue\tests\_generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

use PrivateIT\modules\mailQueue\tests\Helper\Functional;

trait FunctionalTesterActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();

    
}
